# Technical settings
TARGET_HZ = 15 #FPS
DT = 1.0 / TARGET_HZ
OCR_BACKEND = "tesseract"  # "tesseract" or "easyocr"

# Master Debug Overlay + Settings
SHOW_MASTER_DEBUG_OVERLAY = True
MASTER_OVERLAY_SHOW_PARTICIPANTS = True
MASTER_OVERLAY_SHOW_PARTICIPANT_LEGEND = True
MASTER_OVERLAY_HIDE_EMPTY_SLOTS = True
MASTER_OVERLAY_SHOW_INITIATIVE = True
MASTER_OVERLAY_SHOW_PIPS = False
MASTER_OVERLAY_SHOW_BUTTON_LIST = True

# Individual Debug Overlays
SHOW_CAPTURE = False
SHOW_INITIATIVE_OVERLAY = False
SHOW_PARTICIPANTS_OVERLAY = False
SHOW_PIPDETECTION_OVERLAY = False
SHOW_BUTTON_OVERLAY = False

# Debug Dump Toggles
DEBUG_DUMP_OCR = False
DEBUG_DUMP_OCR_MAX = 1
DEBUG_DUMP_HEALTH_ROI = False
DEBUG_DUMP_EMPTY_NAME_ROI = False
DEBUG_DUMP_INITIATIVE_ROI = False
DEBUG_DUMP_SIGIL_ROI = False
DEBUG_DUMP_SCHOOL_ROI = True
DEBUG_DUMP_BUTTON_ROI = False

# Console Debug Output
DEBUG_PRINT_HEALTH_OCR = True
DEBUG_PRINT_NAME_OCR = True
DEBUG_PRINT_STATE_CHANGES = True

# Data Refresh Values
PARTICIPANT_OCCUPANCY_REFRESH_S = 5.0
PARTICIPANT_DETAILS_REFRESH_S = 3.0
INITIATIVE_CAPTURE_WINDOW_S = 3.0
INITIATIVE_STABLE_HOLD_S = 2.0
